name: Netlify

on:
    push:
        branches:
            - develop

jobs:
    build:
        name: 'Build application'
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - name: Use Node.js ${{ matrix.node-version }}
              uses: actions/setup-node@v1
              with:
                  node-version: 14.x
            - run: npm ci
            - run: npm run build --if-present
            - run: npm test
            - uses: actions/upload-artifact@v1
              name: Upload build as artifact
              if: always()
              with:
                  name: application-dist
                  path: ./dist
    deploy-on-netlify:
        name: Publish to Netlify
        if: github.event_name == 'push' && github.ref == 'refs/heads/develop'
        needs: build
        runs-on: ubuntu-latest
        steps:
            - uses: actions/download-artifact@v2
              with:
                  name: application-dist
                  path: ./dist
            - name: Deploy production to Netlify
              uses: South-Paw/action-netlify-deploy@v1.0.4
              with:
                  github-token: ${{ secrets.GITHUB_TOKEN }}
                  netlify-auth-token: ${{ secrets.NETLIFY_AUTH_TOKEN }}
                  netlify-site-id: ${{ secrets.NETLIFY_SITE_ID }}
                  build-dir: './dist'
                  comment-on-commit: true
